### ISSUE TITLE
Cannot initialize submodules

### ISSUE THREAD

**Issue by Neverlord** [biicode/biicode#25]
The guide published at http://biicode.github.io/biicode/ does not work. The submodules are referenced as `git@...`, which means "external" developer are not allowed to access this URL. A possible fix would be to use the HTTPS-URLs instead.

The second step on the homepage, i.e., `git submodule update --init --recursive`, fails for this reason.

**Comment by Manu343726** [comment]
@Neverlord I have my own https submodules fork since I usually work through https https://github.com/Manu343726/biicode-https, I have submitted a PR to merge my changes on the remotes. That should fix the problem.
