### ISSUE TITLE
ADD_BII_TARGETS() ramp bug? Related to bii_tests?

### ISSUE THREAD

**Issue by Manu343726** [biicode/biicode#7]
When porting @pfultz2's Tick to biicode, using Fit CMakeLists.txt file as reference, I changed `INIT_BIICODE_BLOCK()` and `ADD_BIICODE_TARGETS()` deprecated calls by `ADD_BII_TARGETS()`.  
Now `bii configure` call fails with 

``` 
CMake Error: CMake can not determine linker language for target: manu343726_tick_test_test
CMake Error: Cannot determine link language for target "manu343726_tick_test_test".
```
Note with old deprecated macros it works perfectly.

Here's my fork [`CMakeLists.txt`](https://github.com/Manu343726/Tick/blob/bii/CMakeLists.txt) file.

**Comment by lasote** [comment]
With new ADD_BII_TARGETS there is not more dummy.cpp. the test that fails is a header with a main() :( so, there is not cpp or c to link. Main in a header? Why?

https://github.com/Manu343726/Tick/blob/master/test/test.h

**Comment by Manu343726** [comment]
It's a common `main()` function included in all test files

**Comment by lasote** [comment]
Arf. Soooo triky. Just exclude these files from mains in biicode.conf . i think that if you want to launch the tests a cpp is needed.

**Comment by Manu343726** [comment]
Ok, worked. Thanks lasote. Have a good weekend.

**Comment by lasote** [comment]
Oh! I see it now. Tests cpp include test.h
So i think exclude test.h from mains should be enought

**Comment by drodri** [comment]
ACtually it seems a bug in https://github.com/biicode/client/blob/develop/dev/mains.py#L38: 
```
    for main_cell in cells_with_main:
        # filtering out headers
        if BiiType.isCppHeader(main_cell.name.extension):
            output.info("skipping main function in header file %s" % main_cell.name)
        mains[main_cell.name] = _compute_main_info(main_cell, cells, settings)
```

C++ Headers cannot define an entry point, so that code intended to skip it, but actually fails to do so.

Should we open an issue with this?
